### PR TITLE
Basics of continuous uniform + details for geometric function

### PR DESCRIPTION
**Pull request by brunaw**
Here I'm ignoring the different parametrizations for the geometric and using the one that makes more sense to me :)

### CODE REVIEW

**Comment by alexpghayes** [comment]
Thank you!

**Comment by alexpghayes** [comment]
Will you add yourself as contributor in `DESCRIPTION` and then I'll merge?

**Comment by brunaw** [comment]
Definitely! Are you ok with me ignoring multiple parametrisations for the geometric?

**Comment by alexpghayes** [comment]
Yep!

**Comment by brunaw** [comment]
done :)

**Pull request merged**
