### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
WIP Do not merge.

@alexpghayes Are you happy with the coverage of Bernoulli? If yes I'll fill in the other distributions.

### CODE REVIEW

**Comment by alexpghayes** [comment]
This looks fantastic!

At some point we'll need probabilistic tests for samplers, but I don't know how to that and don't want to worry about it just yet.

**Comment by EmilHvitfeldt** [comment]
Found a bug, and got the coverage over 90%. You can merge whenever you are ready

**Comment by alexpghayes** [comment]
Omg this is incredible! Thaaaaaank you!

**Comment by 1danjordan** [comment]
Serious work - well done Emil!

**Pull request merged**
